upstream upstream_cloudflare_pensieve {
    server pensieve-api.amatiasq.workers.dev:443;
}

server {
    listen 80;

    location /auth {
        # TODO: remove `set` instruction
        set $upstream upstream_cloudflare_pensieve;
        proxy_pass https://$upstream;
        proxy_ssl_name pensieve-api.amatiasq.workers.dev;
        proxy_set_header x-forwarded-host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host pensieve-api.amatiasq.workers.dev;
    }

    location /commit {
        # TODO: remove `set` instruction
        set $upstream upstream_cloudflare_pensieve;
        proxy_pass https://$upstream;
        proxy_ssl_name pensieve-api.amatiasq.workers.dev;
        proxy_set_header x-forwarded-host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host pensieve-api.amatiasq.workers.dev;
    }

    location /gist {
        proxy_pass https://amatiasq.github.io;
        rewrite (.*) /pensieve/ break;
    }

    location /note {
        proxy_pass https://amatiasq.github.io;
        rewrite (.*) /pensieve/ break;
    }

    location /halt {
        default_type "text/html";
        return 200;
    }

    location / {
        proxy_pass https://amatiasq.github.io;
        rewrite /(.*) /pensieve/$1 break;
    }
}
