name: Deploy server
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd repos/pensieve/src/api
            git reset --hard
            git checkout tmp
            git branch -D main
            git fetch
            git checkout main
            . ~/.nvm/nvm.sh
            nvm use
            npm i
            pm2 restart env.config.js > /dev/null
